#include "countercontroller.h"
#include <iostream>
#include <QUrl>

namespace counter {

CounterController::CounterController(QObject *parent) : Controller(parent) {
	m_host.setHostUrl(QUrl("local:counter")); //NOTE: in reality, this url would be generated by processlauncher so that combined can reach out to the controller across a network

	if (!m_host.enableRemoting(&m_counter)) {
		std::cerr << "Could not enable remoting" << std::endl;
		return;
	} else {
		std::cout << "Enabled remoting" << std::endl;
	}

	connect(&m_counter, &Counter::countChanged, this, &CounterController::counterIncremented);
}

void CounterController::increment() {
	m_counter.increment();
}

void CounterController::initUI() {}

} // namespace counter
